# Generated by Django 3.0 on 2019-12-31 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('name', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Asian', 'Asian'), ('Hispanic', 'Hispanic')], max_length=10)),
                ('color', models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#000000', 'Black'), ('#999999', 'Grey')], max_length=7)),
                ('line_style', models.CharField(choices=[('--', 'lines'), ('-:', 'double dotted lines'), ('-.', 'dotted lines')], max_length=3)),
                ('size', models.IntegerField()),
                ('loan_demand', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#000000', 'Black'), ('#999999', 'Grey')], max_length=7)),
                ('line_style', models.CharField(choices=[('--', 'lines'), ('-:', 'double dotted lines'), ('-.', 'dotted lines')], max_length=3)),
                ('score_shift', models.IntegerField(default=0)),
                ('utility_repaid', models.FloatField(default=1)),
                ('utility_default', models.FloatField(default=-4)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#000000', 'Black'), ('#999999', 'Grey')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('score_range_min', models.IntegerField(default=300)),
                ('score_range_max', models.IntegerField(default=850)),
                ('repay_score', models.IntegerField(default=75)),
                ('default_score', models.IntegerField(default=-150)),
                ('max_ir_range', models.FloatField(default=0.5)),
                ('min_ir_range', models.FloatField(default=0.001)),
                ('plane_range_max', models.FloatField(default=1)),
                ('plane_range_min', models.FloatField(default=0)),
                ('plane_slice_step', models.FloatField(default=0.01)),
                ('step', models.IntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Policy')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('real_score', models.IntegerField()),
                ('ir_limit', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Applicant_group')),
            ],
        ),
    ]
