# Generated by Django 3.0 on 2019-12-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='policy',
            field=models.IntegerField(choices=[(0, 'Maximum utility'), (1, 'Demographic parity'), (2, 'Equal opportunity')], default=0),
        ),
    ]
