# Generated by Django 3.0 on 2020-01-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20191231_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='step',
        ),
        migrations.AddField(
            model_name='bank',
            name='hs_interest_rate',
            field=models.IntegerField(default=0.06),
        ),
        migrations.AddField(
            model_name='bank',
            name='ls_interest_rate',
            field=models.IntegerField(default=0.15),
        ),
        migrations.AlterField(
            model_name='applicant_group',
            name='line_style',
            field=models.CharField(choices=[('-', '- solid line'), (':', ': dotted line'), ('--', '-- dashed line'), ('-.', '-. dashdot line')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bank',
            name='line_style',
            field=models.CharField(choices=[('-', '- solid line'), (':', ': dotted line'), ('--', '-- dashed line'), ('-.', '-. dashdot line')], max_length=3),
        ),
        migrations.AlterField(
            model_name='market',
            name='policy',
            field=models.IntegerField(choices=[(0, '0: Maximum utility'), (1, '1: Demographic parity'), (2, '2: Equal opportunity')], default=0),
        ),
    ]
