# Generated by Django 3.0 on 2020-01-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200102_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='hs_interest_rate',
            new_name='high_score_interest_rate',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='ls_interest_rate',
            new_name='low_score_interest_rate',
        ),
    ]
