# Generated by Django 3.0 on 2020-01-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200102_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='policy',
            field=models.CharField(choices=[('Max. utility', 'Maximum utility'), ('Dem. parity', 'Demographic parity'), ('Equal opportunity', 'Equal opportunity')], max_length=40),
        ),
    ]
