# Generated by Django 3.0 on 2020-01-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200102_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='policy_color',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#4E73DF', 'Blue'), ('#000000', 'Black'), ('#999999', 'Grey')], default='#dsdsds', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant_group',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#4E73DF', 'Blue'), ('#000000', 'Black'), ('#999999', 'Grey')], max_length=7),
        ),
        migrations.AlterField(
            model_name='bank',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#4E73DF', 'Blue'), ('#000000', 'Black'), ('#999999', 'Grey')], max_length=7),
        ),
        migrations.AlterField(
            model_name='policy',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#4E73DF', 'Blue'), ('#000000', 'Black'), ('#999999', 'Grey')], max_length=7),
        ),
    ]
