# Generated by Django 3.0 on 2020-01-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20200102_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='high_score_interest_rate',
            field=models.FloatField(default=0.06),
        ),
        migrations.AlterField(
            model_name='bank',
            name='low_score_interest_rate',
            field=models.FloatField(default=0.15),
        ),
    ]
