# Generated by Django 3.0 on 2020-01-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20200102_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_group',
            name='error_rate',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='applicant_group',
            name='interest_rate_limit',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='applicant_group',
            name='score_error',
            field=models.IntegerField(default=150),
        ),
    ]
